### ISSUE TITLE
Documentation or Implementation details 

### ISSUE THREAD

**Issue by aminullah6264** [ZHANG-SHI-CHANG/Dehaze#1]
Dear Chang,

Can you please share paper, documentation, or any implementation details of this project. 

Thanks

**Comment by ZHANG-SHI-CHANG** [comment]
the main func is in code, it is easy to understand ^-^
![image](https://user-images.githubusercontent.com/30692249/83103493-645f1b00-a0e9-11ea-8c95-e5e777ff3f48.png)

**Comment by aminullah6264** [comment]
Dear, I run the code is very well working. However, I want to know the theoretical process inside the code.  Therefore, if you have any text about this... or this algorithm is from any paper. Please refer it to me.

Thanks.

**Comment by aminullah6264** [comment]
Dear, I run the code and it is very well working. However, I want to know the theoretical process inside the code. Therefore, if you have any text about this... or this algorithm is from any paper. Please refer it to me.

Thanks.

**Comment by ZHANG-SHI-CHANG** [comment]
> Dear, I run the code and it is very well working. However, I want to know the theoretical process inside the code. Therefore, if you have any text about this... or this algorithm is from any paper. Please refer it to me.
> 
> Thanks.

ok, the theoretical is easy, remove the highest pixel value and the lowest pixel value, other pixel value do a linear map, like the follow image
![image](https://user-images.githubusercontent.com/30692249/83321361-a0c57f00-a281-11ea-912d-2764f4968ed6.png)
